### ISSUE TITLE
How much memory SEResnextUnet50_OC_scSE_hyper need?

### ISSUE THREAD

**Issue by zxshi** [liaopeiyuan/ml-arsenal-public#1]
I have two 2080ti with 11G each GPU, but when I used SEResnextUnet50_OC_scSE_hyper, I got this error:
Traceback (most recent call last):
  File "aaa.py", line 5, in <module>
    se.run_check_net()
  File "/media/files/networks/SEResnextUnet50_OC_scSE_hyper.py", line 1039, in run_check_net
    loss.backward()
  File "/home/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: out of memory

**Comment by liaopeiyuan** [comment]
You'll need a P100 to do the experiments with batch size=16. Also, the ocnet model used for submission was trained by Ding Han, and you may find it here: https://github.com/liaopeiyuan/ml-arsenal-public/blob/master/projects/TGS_salt/DingHan/seresnet50/model_se_resnext50_bn.py

**Comment by zxshi** [comment]
1. Thanks for your reply.
2. The P100 is 16G, my toal memory is 22G, I don't know why get this error?
3. yes, I find thes pretrained model.
